name: Docker OpenUchile Image CI

on:
  push:
    paths:
      - 'openuchile/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Open UChile
        run: docker build ./openuchile --file ./openuchile/Dockerfile --tag ghcr.io/eol-uchile/maintenance-container:openuchile-${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push
        run: |
          docker push ghcr.io/eol-uchile/maintenance-container:openuchile-${GITHUB_SHA}
