name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build . --tag ghcr.io/eol-uchile/maintenance-nginx:${GITHUB_SHA}

      - name: Build Eol
        run: docker build ./eol --file ./eol/Dockerfile --tag eoluchile/eol-edx:${GITHUB_SHA} --tag eoluchile/eol-edx:latest
      
      - name: Build UAbierta
        run: docker build ./uabierta --file ./uabierta/Dockerfile --tag eoluchile/edx-uabierta:${GITHUB_SHA} --tag eoluchile/edx-uabierta:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push
        run: |
          docker push ghcr.io/eol-uchile/maintenance-nginx:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/eol-edx:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/edx-uabierta:${GITHUB_SHA}