name: Docker UAbierta Image CI

on:
  push:
    paths:
      - 'uabierta/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "TS=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build UAbierta
        run: docker build ./uabierta --file ./uabierta/Dockerfile --tag ghcr.io/eol-uchile/maintenance-container:uabierta-${{ env.TS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/eol-uchile/maintenance-container:uabierta-${{ env.TS }}
