name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Eol
        run: docker build ./eol --file ./eol/Dockerfile --tag ghcr.io/eol-uchile/maintenance-container:eol-${GITHUB_SHA}
      
      - name: Build UAbierta
        run: docker build ./uabierta --file ./uabierta/Dockerfile --tag ghcr.io/eol-uchile/maintenance-container:uabierta-${GITHUB_SHA}

      - name: Build Virtual labx CLA
        run: docker build ./virtuallbax --file ./virtuallbax/Dockerfile --tag ghcr.io/eol-uchile/maintenance-container:virtuallabx-${GITHUB_SHA}

      - name: Build Open UChile
        run: docker build ./openuchile --file ./openuchile/Dockerfile --tag ghcr.io/eol-uchile/maintenance-container:openuchile-${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push
        run: |
          docker push ghcr.io/eol-uchile/maintenance-container:eol-${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/maintenance-container:uabierta-${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/maintenance-container:virtuallabx-${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/maintenance-container:openuchile-${GITHUB_SHA}