name: Docker EOL Image CI

on:
  push:
    paths:
      - 'eol/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Eol
        run: docker build ./eol --file ./eol/Dockerfile --tag ghcr.io/eol-uchile/maintenance-container:eol-${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/eol-uchile/maintenance-container:eol-${GITHUB_SHA}
